### ISSUE TITLE
안녕하세요. 반갑습니다. 작성하느라 고생 많으셨습니다. 

### ISSUE THREAD

**Issue by corazzon** [kkkapuq/kernal360_preAssignment#1]
- 문서화를 잘 작성해 주셨습니다. 이미지가 깨지는 부분이 있는데 확인해 보세요. 
- .gitignore 설정이 되어 있지 않습니다. 환경설정 등의 파일은 커밋되지 않도록 관리해 주세요. 
- 클래스와 메서드에 대한 주석을 잘 작성해 주셨습니다.
- isValidDate 메서드는 static으로 선언되어 있어, 클래스 레벨에서 사용 가능합니다. 이런 유틸리티성 메서드는 별도의 유틸리티 클래스로 분리하는 것도 고려해 볼 수 있습니다.
- 교육 및 경력 정보 입력 부분에서 유사한 로직이 반복되고 있습니다. 이런 반복적인 코드는 별도의 메서드로 분리하거나 리팩토링하여 중복을 줄일 수 있습니다.
- 일부 메서드 (inputPersonalInfo, inputCareerList 등)가 다소 길어 보입니다. 가능하다면 이들을 더 작은 단위로 분리하는 것을 고려해 보는 것이 좋습니다.
- 근무 기간에 대한 입력 형식을 검사하는 부분에서 careerInfo[0].length() != 21와 같은 하드코딩된 숫자가 사용되었습니다. 이런 숫자는 상수로 선언하여 코드의 가독성을 높일 수 있습니다.
- 사용자가 입력을 할 때, 어떤 형식으로 입력해야 하는지 더 구체적인 안내 메시지를 제공하면 좋겠습니다.

**Comment by kkkapuq** [comment]
섬세한 리뷰 감사드립니다.
추후 개발 시에도 꼭 참고하도록 하겠습니다!
